spring:
    datasource:
        url: jdbc:mysql://localhost:3306/java?characterEncoding=utf8
        username: root
        password: gaomin521
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
           ddl-auto: update
           naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                  dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9000

